import type { Metadata } from "next";
import { Caveat_Brush, Geist, Geist_Mono, Matemasie, Pacifico } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const matemasie = Matemasie({
  variable: "--font-matemasie",
  weight: '400',
  subsets: ["latin"],
});


const caveat = Caveat_Brush({
  variable: "--font-caveat",
  weight: '400',
  subsets: ["latin"],
});


const pacifico = Pacifico({
  variable: "--font-pacifico",
  weight: '400',
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} 
        ${matemasie.variable} ${caveat.variable} ${pacifico.variable}
        antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
